import DataTablePage from "@/components/common/DataTable/DataTablePage";

function TheLoaiView() {
  return (
    <DataTablePage
      apiModule="theloai"
      columns={[
        { key: "MaTL", label: "MaTL", displayLabel: "Mã thể loại", autoGenerated: true, primaryKey: true, widthValue: 130 },
        { key: "TenTL", label: "TenTL", displayLabel: "Tên thể loại", widthValue: 220 },
      ]}
      entityName="Thể loại"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã hoặc tên thể loại..."
      title="Quản lý Thể loại"
    />
  );
}

export default TheLoaiView;
