import DataTablePage from "@/components/common/DataTable/DataTablePage";

function NgonNguView() {
  return (
    <DataTablePage
      apiModule="ngonngu"
      columns={[
        { key: "MaNN", label: "MaNN", displayLabel: "Mã ngôn ngữ", autoGenerated: true, primaryKey: true, widthValue: 130 },
        { key: "TenNN", label: "TenNN", displayLabel: "Tên ngôn ngữ", widthValue: 190 },
      ]}
      entityName="Ngôn ngữ"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm tên ngôn ngữ..."
      title="Quản lý Ngôn ngữ"
    />
  );
}

export default NgonNguView;
