import DataTablePage from "@/components/common/DataTablePage";

function NhanVienView() {
  return (
    <DataTablePage
      apiModule="nhanvien"
      columns={[
        { key: "MaNV", label: "MaNV", tableLabel: "Mã NV", displayLabel: "Mã nhân viên", autoGenerated: true, primaryKey: true, widthValue: 92 },
        { key: "TenNV", label: "TenNV", tableLabel: "Nhân viên", displayLabel: "Tên nhân viên", widthValue: 118 },
        { key: "QueQuan", label: "QueQuan", displayLabel: "Quê quán", widthValue: 106 },
        {
          key: "GioiTinh",
          label: "GioiTinh",
          tableLabel: "GT",
          displayLabel: "Giới tính",
          options: [
            { label: "Nam", value: "Nam" },
            { label: "Nữ", value: "Nữ" },
            { label: "Khác", value: "Khác" },
          ],
          widthValue: 64,
        },
        { key: "NamSinh", label: "NamSinh", tableLabel: "Năm sinh", displayLabel: "Năm sinh", widthValue: 82 },
        {
          key: "VaiTro",
          label: "VaiTro",
          displayLabel: "Vai trò",
          badge: true,
          options: [
            { label: "Quản lý", value: "Quản lý" },
            { label: "Thủ thư", value: "Thủ thư" },
          ],
          widthValue: 118,
        },
        { key: "Email", label: "Email", displayLabel: "Email", widthValue: 118 },
        { key: "Sdt", label: "Sdt", tableLabel: "SĐT", displayLabel: "Số điện thoại", widthValue: 96 },
        { key: "User", label: "User", tableLabel: "Tài khoản", displayLabel: "Tên đăng nhập", widthValue: 104 },
        {
          key: "Pass",
          label: "Pass",
          displayLabel: "Mật khẩu mới",
          inputType: "password",
          tableHidden: true,
          detailHidden: true,
          requiredOnCreate: true,
          clearOnEdit: true,
          keepExistingWhenBlank: true,
          placeholder: "Nhập mật khẩu mới",
        },
      ]}
      entityName="Nhân viên"
      searchPlaceholder="Tìm mã, tên hoặc tên đăng nhập..."
      title="Quản lý Nhân viên"
    />
  );
}

export default NhanVienView;
