import DataTablePage from "@/components/common/DataTable/DataTablePage";

function KeSachView() {
  return (
    <DataTablePage
      apiModule="kesach"
      columns={[
        { key: "MaViTri", label: "MaViTri", displayLabel: "Mã vị trí", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenKe", label: "TenKe", displayLabel: "Tên kệ", widthValue: 190 },
        { key: "MoTa", label: "MoTa", displayLabel: "Mô tả", widthValue: 250 },
      ]}
      entityName="Kệ sách"
      searchPlaceholder="Tìm mã kệ hoặc tên kệ..."
      title="Quản lý Kệ sách"
    />
  );
}

export default KeSachView;
