import DataTablePage from "@/components/common/DataTablePage";

function KhoaView() {
  return (
    <DataTablePage
      apiModule="khoa"
      columns={[
        { key: "MaKhoa", label: "MaKhoa", displayLabel: "Mã khoa", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenKhoa", label: "TenKhoa", displayLabel: "Tên khoa", widthValue: 250 },
      ]}
      entityName="Khoa"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã khoa hoặc tên khoa..."
      title="Quản lý Khoa"
    />
  );
}

export default KhoaView;
