import DataTablePage from "@/components/common/DataTable/DataTablePage";
import { useApiLists } from "@/hooks/useApiLists";
import { getSachStatus } from "@/views/sach/sachUtils";
import { createLookup } from "@/utils/lookup";

const LOOKUP_MODULES = ["tacgia", "theloai", "nhaxuatban", "ngonngu", "kesach"];

function SachView() {
  const { data } = useApiLists(LOOKUP_MODULES);
  const authors = data.tacgia ?? [];
  const categories = data.theloai ?? [];
  const publishers = data.nhaxuatban ?? [];
  const languages = data.ngonngu ?? [];
  const shelves = data.kesach ?? [];

  const authorNames = createLookup(authors, "MaTG", "TenTG");
  const categoryNames = createLookup(categories, "MaTL", "TenTL");
  const publisherNames = createLookup(publishers, "MaNXB", "TenNXB");
  const languageNames = createLookup(languages, "MaNN", "TenNN");
  const shelfNames = createLookup(shelves, "MaViTri", "TenKe");

  return (
    <DataTablePage
      apiModule="sach"
      columns={[
        {
          key: "MaSach",
          label: "MaSach",
          tableLabel: "Mã sách",
          displayLabel: "Mã sách",
          autoGenerated: true,
          primaryKey: true,
          widthValue: 86,
        },
        {
          key: "TenSach",
          label: "TenSach",
          tableLabel: "Tên sách",
          displayLabel: "Tên sách",
          widthValue: 170,
        },
        {
          key: "MaTG",
          label: "MaTG",
          tableLabel: "Tác giả",
          displayLabel: "Tác giả",
          displayValue: (row) => authorNames[row.MaTG] ?? row.MaTG,
          options: authors.map((author) => ({
            label: `${author.MaTG} - ${author.TenTG}`,
            value: author.MaTG,
          })),
          widthValue: 128,
        },
        {
          key: "MaTL",
          label: "MaTL",
          tableLabel: "Thể loại",
          displayLabel: "Thể loại",
          displayValue: (row) => categoryNames[row.MaTL] ?? row.MaTL,
          options: categories.map((category) => ({
            label: `${category.MaTL} - ${category.TenTL}`,
            value: category.MaTL,
          })),
          widthValue: 120,
        },
        {
          key: "MaNXB",
          label: "MaNXB",
          tableLabel: "NXB",
          displayLabel: "Nhà xuất bản",
          displayValue: (row) => publisherNames[row.MaNXB] ?? row.MaNXB,
          options: publishers.map((publisher) => ({
            label: `${publisher.MaNXB} - ${publisher.TenNXB}`,
            value: publisher.MaNXB,
          })),
          widthValue: 130,
        },
        {
          key: "NamXB",
          label: "NamXB",
          tableLabel: "Năm XB",
          displayLabel: "Năm xuất bản",
          inputType: "number",
          widthValue: 82,
        },
        {
          key: "MaNN",
          label: "MaNN",
          tableLabel: "Ngôn ngữ",
          displayLabel: "Ngôn ngữ",
          displayValue: (row) => languageNames[row.MaNN] ?? row.MaNN,
          options: languages.map((language) => ({
            label: `${language.MaNN} - ${language.TenNN}`,
            value: language.MaNN,
          })),
          widthValue: 100,
        },
        {
          key: "MaViTri",
          label: "MaViTri",
          tableLabel: "Kệ sách",
          displayLabel: "Kệ sách",
          displayValue: (row) => shelfNames[row.MaViTri] ?? row.MaViTri,
          options: shelves.map((shelf) => ({
            label: `${shelf.MaViTri} - ${shelf.TenKe}`,
            value: shelf.MaViTri,
          })),
          widthValue: 104,
        },
        {
          key: "SoLuong",
          label: "SoLuong",
          tableLabel: "SL",
          displayLabel: "Số lượng",
          inputType: "number",
          widthValue: 70,
        },
        {
          key: "TrangThaiSach",
          label: "TrangThaiSach",
          tableLabel: "Trạng thái",
          displayLabel: "Trạng thái",
          displayValue: (row) => getSachStatus(row.SoLuong),
          formHidden: true,
          badge: true,
          widthValue: 94,
        },
      ]}
      entityName="Sách"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã sách, tên sách, tác giả..."
      title="Quản lý Sách"
    />
  );
}

export default SachView;
