import DataTablePage from "@/components/common/DataTable/DataTablePage";
import { useApiLists } from "@/hooks/useApiLists";
import { getSachStatus } from "@/views/sach/sachUtils";
import { createLookup } from "@/utils/lookup";
import { api } from "@/lib/api";
import { getNextGeneratedValue } from "@/components/common/dataTableUtils";

const LOOKUP_MODULES = ["tacgia", "theloai", "nhaxuatban", "ngonngu", "kesach"];

function SachView() {
  const { appendItem, data } = useApiLists(LOOKUP_MODULES);
  const authors = data.tacgia ?? [];
  const categories = data.theloai ?? [];
  const publishers = data.nhaxuatban ?? [];
  const languages = data.ngonngu ?? [];
  const shelves = data.kesach ?? [];

  const authorNames = createLookup(authors, "MaTG", "TenTG");
  const categoryNames = createLookup(categories, "MaTL", "TenTL");
  const publisherNames = createLookup(publishers, "MaNXB", "TenNXB");
  const languageNames = createLookup(languages, "MaNN", "TenNN");
  const shelfNames = createLookup(shelves, "MaViTri", "TenKe");

  async function createRelatedItem({ collection, idKey, module, nameKey, prefix, values }) {
    const payload = {
      ...values,
      [idKey]: getNextGeneratedValue(collection, { key: idKey, generatedPrefix: prefix, generatedWidth: 3 }),
    };
    const response = await api.create(module, payload);
    const item = response.data ?? payload;
    appendItem(module, item);
    return { label: `${item[idKey]} - ${item[nameKey]}`, value: item[idKey] };
  }

  async function createAuthor(values) {
    return createRelatedItem({
      collection: authors,
      idKey: "MaTG",
      module: "tacgia",
      nameKey: "TenTG",
      prefix: "TG",
      values: {
      TenTG: values.TenTG.trim(),
      NamSinh: values.NamSinh ? Number(values.NamSinh) : "",
      GioiTinh: values.GioiTinh,
      QuocTich: values.QuocTich.trim(),
      },
    });
  }

  return (
    <DataTablePage
      apiModule="sach"
      columns={[
        {
          key: "MaSach",
          label: "MaSach",
          tableLabel: "Mã sách",
          displayLabel: "Mã sách",
          autoGenerated: true,
          primaryKey: true,
          widthValue: 86,
        },
        {
          key: "TenSach",
          label: "TenSach",
          tableLabel: "Tên sách",
          displayLabel: "Tên sách",
          widthValue: 170,
        },
        {
          key: "MaTG",
          label: "MaTG",
          tableLabel: "Tác giả",
          displayLabel: "Tác giả",
          displayValue: (row) => authorNames[row.MaTG] ?? row.MaTG,
          options: authors.map((author) => ({
            label: `${author.MaTG} - ${author.TenTG}`,
            value: author.MaTG,
          })),
          quickCreate: {
            entityName: "Tác giả",
            fields: [
              { key: "TenTG", label: "Tên tác giả", fullWidth: true },
              { key: "NamSinh", label: "Năm sinh", inputType: "number", min: 1900, max: new Date().getFullYear(), required: false },
              {
                key: "GioiTinh", label: "Giới tính",
                options: ["Nam", "Nữ", "Khác"].map((value) => ({ label: value, value })),
              },
              { key: "QuocTich", label: "Quốc tịch", defaultValue: "Việt Nam" },
            ],
            label: "Thêm nhanh tác giả",
            nameField: "TenTG",
            onCreate: createAuthor,
          },
          searchable: true,
          widthValue: 128,
        },
        {
          key: "MaTL",
          label: "MaTL",
          tableLabel: "Thể loại",
          displayLabel: "Thể loại",
          displayValue: (row) => categoryNames[row.MaTL] ?? row.MaTL,
          options: categories.map((category) => ({
            label: `${category.MaTL} - ${category.TenTL}`,
            value: category.MaTL,
          })),
          quickCreate: {
            entityName: "Thể loại",
            fields: [{ key: "TenTL", label: "Tên thể loại", fullWidth: true }],
            label: "Thêm nhanh thể loại",
            nameField: "TenTL",
            onCreate: (values) => createRelatedItem({
              collection: categories,
              idKey: "MaTL",
              module: "theloai",
              nameKey: "TenTL",
              prefix: "TL",
              values: { TenTL: values.TenTL.trim() },
            }),
          },
          searchable: true,
          widthValue: 120,
        },
        {
          key: "MaNXB",
          label: "MaNXB",
          tableLabel: "NXB",
          displayLabel: "Nhà xuất bản",
          displayValue: (row) => publisherNames[row.MaNXB] ?? row.MaNXB,
          options: publishers.map((publisher) => ({
            label: `${publisher.MaNXB} - ${publisher.TenNXB}`,
            value: publisher.MaNXB,
          })),
          quickCreate: {
            entityName: "Nhà xuất bản",
            fields: [
              { key: "TenNXB", label: "Tên nhà xuất bản", fullWidth: true },
              { key: "DiaChi", label: "Địa chỉ", fullWidth: true },
              { key: "Email", label: "Email", inputType: "email" },
              { key: "Sdt", label: "Số điện thoại", inputType: "tel", required: false },
            ],
            label: "Thêm nhanh nhà xuất bản",
            nameField: "TenNXB",
            onCreate: (values) => createRelatedItem({
              collection: publishers,
              idKey: "MaNXB",
              module: "nhaxuatban",
              nameKey: "TenNXB",
              prefix: "NXB",
              values: {
                TenNXB: values.TenNXB.trim(),
                DiaChi: values.DiaChi.trim(),
                Email: values.Email.trim(),
                Sdt: values.Sdt.trim(),
              },
            }),
          },
          searchable: true,
          widthValue: 130,
        },
        {
          key: "NamXB",
          label: "NamXB",
          tableLabel: "Năm XB",
          displayLabel: "Năm xuất bản",
          inputType: "number",
          widthValue: 82,
        },
        {
          key: "MaNN",
          label: "MaNN",
          tableLabel: "Ngôn ngữ",
          displayLabel: "Ngôn ngữ",
          displayValue: (row) => languageNames[row.MaNN] ?? row.MaNN,
          options: languages.map((language) => ({
            label: `${language.MaNN} - ${language.TenNN}`,
            value: language.MaNN,
          })),
          quickCreate: {
            entityName: "Ngôn ngữ",
            fields: [{ key: "TenNN", label: "Tên ngôn ngữ", fullWidth: true }],
            label: "Thêm nhanh ngôn ngữ",
            nameField: "TenNN",
            onCreate: (values) => createRelatedItem({
              collection: languages,
              idKey: "MaNN",
              module: "ngonngu",
              nameKey: "TenNN",
              prefix: "NN",
              values: { TenNN: values.TenNN.trim() },
            }),
          },
          searchable: true,
          widthValue: 100,
        },
        {
          key: "MaViTri",
          label: "MaViTri",
          tableLabel: "Kệ sách",
          displayLabel: "Kệ sách",
          displayValue: (row) => shelfNames[row.MaViTri] ?? row.MaViTri,
          options: shelves.map((shelf) => ({
            label: `${shelf.MaViTri} - ${shelf.TenKe}`,
            value: shelf.MaViTri,
          })),
          quickCreate: {
            entityName: "Kệ sách",
            fields: [
              { key: "TenKe", label: "Tên kệ", fullWidth: true },
              { key: "MoTa", label: "Mô tả", fullWidth: true },
            ],
            label: "Thêm nhanh kệ sách",
            nameField: "TenKe",
            onCreate: (values) => createRelatedItem({
              collection: shelves,
              idKey: "MaViTri",
              module: "kesach",
              nameKey: "TenKe",
              prefix: "KS",
              values: { TenKe: values.TenKe.trim(), MoTa: values.MoTa.trim() },
            }),
          },
          searchable: true,
          widthValue: 104,
        },
        {
          key: "SoLuong",
          label: "SoLuong",
          tableLabel: "SL",
          displayLabel: "Số lượng",
          inputType: "number",
          widthValue: 70,
        },
        {
          key: "TrangThaiSach",
          label: "TrangThaiSach",
          tableLabel: "Trạng thái",
          displayLabel: "Trạng thái",
          displayValue: (row) => getSachStatus(row.SoLuong),
          formHidden: true,
          badge: true,
          widthValue: 94,
        },
      ]}
      entityName="Sách"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã sách, tên sách, tác giả..."
      title="Quản lý Sách"
    />
  );
}

export default SachView;
