import DataTablePage from "@/components/common/DataTablePage";
import { useApiLists } from "@/hooks/useApiLists";
import { api } from "@/lib/api";
import GiaHanTheDialog from "@/views/thethuvien/components/GiaHanTheDialog";
import { getCardStatus } from "@/views/thethuvien/theThuVienUtils";
import { createLookup } from "@/utils/lookup";

function TheThuVienView() {
  const { data } = useApiLists(["docgia"]);
  const readers = data.docgia ?? [];
  const readerNames = createLookup(readers, "MaDG", "TenDG");

  return (
    <DataTablePage
      apiModule="thethuvien"
      columns={[
        { key: "MaThe", label: "MaThe", displayLabel: "Mã thẻ", autoGenerated: true, primaryKey: true, widthValue: 120 },
        {
          key: "MaDG", label: "MaDG", displayLabel: "Độc giả",
          displayValue: (row) => readerNames[row.MaDG] ?? row.MaDG,
          options: readers.map((reader) => ({ label: `${reader.MaDG} - ${reader.TenDG}`, value: reader.MaDG })),
          widthValue: 190,
        },
        { key: "NgayCap", label: "NgayCap", displayLabel: "Ngày cấp", inputType: "date", widthValue: 140 },
        { key: "NgayHetHan", label: "NgayHetHan", displayLabel: "Ngày hết hạn", inputType: "date", widthValue: 160 },
        {
          key: "TrangThai", label: "TrangThai", displayLabel: "Trạng thái", badge: true,
          options: ["Còn hiệu lực", "Hết hạn", "Tạm khóa"].map((value) => ({ label: value, value })),
          widthValue: 170,
        },
      ]}
      entityName="Thẻ thư viện"
      renderDetailExtra={({ row, updateRow }) => (
        <GiaHanTheDialog
          onRenew={async (NgayHetHan) => {
            const updated = {
              MaThe: row.MaThe,
              MaDG: row.MaDG,
              NgayCap: row.NgayCap,
              NgayHetHan,
              TrangThai: getCardStatus(NgayHetHan),
            };
            const response = await api.update("thethuvien", row.MaThe, updated);
            updateRow(response.data ?? updated);
          }}
          row={row}
        />
      )}
      searchPlaceholder="Tìm mã thẻ hoặc độc giả..."
      title="Quản lý Thẻ thư viện"
    />
  );
}

export default TheThuVienView;
