import { getNextGeneratedValue } from "@/components/common/dataTableUtils";
import { hasErrors, validateGenericEntityForm } from "@/utils/formValidation";

const DATA_SHEET = "DuLieu";
const GUIDE_SHEET = "HuongDan";
const MAX_IMPORT_ROWS = 1000;
const MAX_FILE_SIZE = 10 * 1024 * 1024;
const UNIQUE_FIELD_KEYS = new Set(["email", "sdt", "user"]);
const NUMBER_FIELD_KEYS = new Set(["namsinh", "namxb", "soluong"]);

function isNumberColumn(column) {
  return column.inputType === "number" || NUMBER_FIELD_KEYS.has(column.key.toLowerCase());
}

function getImportColumns(columns) {
  return columns.filter(
    (column) =>
      !column.formHidden &&
      !column.excelHidden &&
      !(column.primaryKey && column.autoGenerated) &&
      !column.readOnly &&
      !column.readOnlyOnCreate,
  );
}

function getExportColumns(columns) {
  return columns.filter(
    (column) =>
      !column.excelHidden &&
      (column.excelOnly || !column.detailHidden),
  );
}

function getLabel(column) {
  return column.displayLabel ?? column.tableLabel ?? column.label ?? column.key;
}

function getOptionName(option) {
  const label = String(option.label ?? option.value ?? "").trim();
  const codePrefix = `${option.value} - `;
  return label.startsWith(codePrefix) ? label.slice(codePrefix.length).trim() : label;
}

function safeFileName(value) {
  return String(value)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function download(buffer, filename) {
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  window.setTimeout(() => URL.revokeObjectURL(link.href), 0);
}

function styleHeader(row) {
  row.height = 24;
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF97316" } };
    cell.alignment = { horizontal: "center", vertical: "middle" };
    cell.border = {
      bottom: { style: "thin", color: { argb: "FFCBD5E1" } },
    };
  });
}

function addGuideSheet(workbook, columns, entityName, isTemplate) {
  const sheet = workbook.addWorksheet(GUIDE_SHEET, { views: [{ state: "frozen", ySplit: 4 }] });
  sheet.mergeCells("A1:E1");
  sheet.getCell("A1").value = `${isTemplate ? "HƯỚNG DẪN NHẬP" : "THÔNG TIN DỮ LIỆU"} ${String(entityName).toUpperCase()}`;
  sheet.getCell("A1").font = { bold: true, size: 15, color: { argb: "FFC2410C" } };
  sheet.getCell("A2").value = isTemplate
    ? "Chỉ nhập dữ liệu tại sheet DuLieu. Không đổi tên sheet, tên cột hoặc thứ tự cột."
    : "Đây là file xuất dữ liệu. Khi cần nhập mới, hãy tải file mẫu chuẩn từ nút Nhập Excel.";
  sheet.mergeCells("A2:E2");
  sheet.getCell("A3").value = "Mã bản ghi được hệ thống tự sinh. Số điện thoại phải đặt ở dạng văn bản để giữ số 0 đầu.";
  sheet.mergeCells("A3:E3");
  sheet.addRow(["Cột trong file", "Trường dữ liệu", "Bắt buộc", "Kiểu dữ liệu", "Giá trị hợp lệ / ghi chú"]);
  styleHeader(sheet.getRow(4));

  columns.forEach((column) => {
    const options = typeof column.options === "function" ? [] : column.options ?? [];
    const required = column.autoGenerated ? "Không (tự sinh)" : column.required === false ? "Không" : "Có";
    const type = isNumberColumn(column)
      ? "Số"
      : column.inputType === "date"
        ? "Ngày (YYYY-MM-DD)"
        : "Văn bản";
    const note = options.length
      ? options.map(getOptionName).join(", ")
      : column.dependsOn
        ? `Tên phải thuộc ${getLabel(columns.find((item) => item.key === column.dependsOn) ?? { key: column.dependsOn })} đã nhập cùng dòng`
        : column.maxLength
          ? `Tối đa ${column.maxLength} ký tự`
          : "";
    sheet.addRow([getLabel(column), column.key, required, type, note]);
  });

  sheet.columns = [
    { width: 22 },
    { width: 28 },
    { width: 18 },
    { width: 22 },
    { width: 55 },
  ];
  sheet.eachRow((row) => {
    row.alignment = { vertical: "top", wrapText: true };
  });
}

function configureDataSheet(sheet, columns, includeValidations = true) {
  sheet.views = [{ state: "frozen", ySplit: 1 }];
  sheet.addRow(columns.map(getLabel));
  styleHeader(sheet.getRow(1));
  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: columns.length },
  };

  columns.forEach((column, index) => {
    const excelColumn = sheet.getColumn(index + 1);
    excelColumn.width = Math.max(14, Math.min(32, getLabel(column).length + 6));
    excelColumn.numFmt = isNumberColumn(column) ? "0" : "@";
    const options = typeof column.options === "function" ? [] : column.options ?? [];
    const optionNames = options.map(getOptionName);
    const optionList = optionNames.join(",");
    const canUseInlineList = optionNames.every((name) => !name.includes(",") && !name.includes('"'));
    if (includeValidations && options.length && optionList.length <= 255 && canUseInlineList) {
      for (let row = 2; row <= MAX_IMPORT_ROWS + 1; row += 1) {
        sheet.getCell(row, index + 1).dataValidation = {
          type: "list",
          allowBlank: column.required === false || column.autoGenerated,
          formulae: [`"${optionList}"`],
          showErrorMessage: true,
          errorTitle: "Giá trị không hợp lệ",
          error: "Hãy chọn một giá trị trong danh sách.",
        };
      }
    }
  });
}

async function createWorkbook(columns, entityName, includeValidations = true) {
  const { default: ExcelJS } = await import("exceljs");
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Thư viện UTT";
  workbook.created = new Date();
  const dataSheet = workbook.addWorksheet(DATA_SHEET);
  configureDataSheet(dataSheet, columns, includeValidations);
  addGuideSheet(workbook, columns, entityName, includeValidations);
  return { dataSheet, workbook };
}

export async function downloadEntityTemplate({ columns, entityName }) {
  const importColumns = getImportColumns(columns);
  const { workbook } = await createWorkbook(importColumns, entityName);
  const buffer = await workbook.xlsx.writeBuffer();
  download(buffer, `mau-nhap-${safeFileName(entityName)}.xlsx`);
}

export async function exportEntityExcel({ columns, entityName, rows }) {
  const exportColumns = getExportColumns(columns);
  const { dataSheet, workbook } = await createWorkbook(exportColumns, entityName, false);
  rows.forEach((row) => {
    dataSheet.addRow(exportColumns.map((column) => normalizeExportValue(row, column)));
  });
  const buffer = await workbook.xlsx.writeBuffer();
  const date = new Date().toISOString().slice(0, 10).replaceAll("-", "");
  download(buffer, `${safeFileName(entityName)}-${date}.xlsx`);
}

function normalizeExportValue(row, column) {
  const value = column.displayValue ? column.displayValue(row) : row[column.key];
  if (value === null || value === undefined) return "";
  if (column.inputType === "date") return String(value).slice(0, 10);
  return value;
}

function readCellValue(cell, column, rowNumber) {
  let value = cell.value;
  if (value && typeof value === "object") {
    if (value instanceof Date) {
      const year = value.getFullYear();
      const month = String(value.getMonth() + 1).padStart(2, "0");
      const day = String(value.getDate()).padStart(2, "0");
      value = `${year}-${month}-${day}`;
    } else if (Array.isArray(value.richText)) {
      value = value.richText.map((part) => part.text).join("");
    } else if (value.text !== undefined) {
      value = value.text;
    } else if (value.result !== undefined) {
      value = value.result;
    } else {
      throw new Error(`Dòng ${rowNumber}, cột ${column.key}: kiểu ô Excel không được hỗ trợ.`);
    }
  }

  if (value === null || value === undefined) return "";
  if (isNumberColumn(column)) {
    if (String(value).trim() === "") return "";
    const number = Number(value);
    if (!Number.isFinite(number)) {
      throw new Error(`Dòng ${rowNumber}, cột ${column.key}: phải là số hợp lệ.`);
    }
    if (column.min !== undefined && number < column.min) {
      throw new Error(`Dòng ${rowNumber}, cột ${column.key}: không được nhỏ hơn ${column.min}.`);
    }
    if (column.max !== undefined && number > column.max) {
      throw new Error(`Dòng ${rowNumber}, cột ${column.key}: không được lớn hơn ${column.max}.`);
    }
    return number;
  }
  const text = String(value).trim();
  if (column.inputType === "date" && text) {
    const match = text.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    const date = match ? new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3])) : null;
    if (
      !match ||
      date.getFullYear() !== Number(match[1]) ||
      date.getMonth() !== Number(match[2]) - 1 ||
      date.getDate() !== Number(match[3])
    ) {
      throw new Error(`Dòng ${rowNumber}, cột ${column.key}: ngày phải đúng định dạng YYYY-MM-DD.`);
    }
  }
  return text;
}

function validateHeaders(sheet, columns) {
  const actual = [];
  const lastColumn = Math.max(sheet.actualColumnCount, sheet.getRow(1).cellCount);
  for (let index = 1; index <= lastColumn; index += 1) {
    actual.push(String(sheet.getRow(1).getCell(index).value ?? "").trim());
  }
  const expected = columns.map(getLabel);
  if (actual.length !== expected.length || actual.some((value, index) => value !== expected[index])) {
    throw new Error(
      `Sai cấu trúc cột. Hãy dùng đúng file mẫu. Thứ tự cần có: ${expected.join(", ")}.`,
    );
  }
}

function applyDefaults(row, columns, acceptedRows, existingRows) {
  columns.filter((column) => !column.formHidden).forEach((column) => {
    if (row[column.key] !== undefined && row[column.key] !== "") return;
    if (column.autoGenerated) {
      row[column.key] = getNextGeneratedValue([...existingRows, ...acceptedRows], column);
    } else if (typeof column.defaultValue === "function") {
      row[column.key] = column.defaultValue();
    } else if (column.defaultValue !== undefined) {
      row[column.key] = column.defaultValue;
    }
  });
}

function validateOptions(row, columns, rowNumber) {
  columns.forEach((column) => {
    if (!column.options || row[column.key] === "" || row[column.key] === undefined) return;
    const options = typeof column.options === "function" ? column.options(row) : column.options;
    const input = normalizeLookupValue(row[column.key]);
    const byCode = options.filter((option) => normalizeLookupValue(option.value) === input);
    const byName = options.filter((option) => normalizeLookupValue(getOptionName(option)) === input);
    const matches = byCode.length ? byCode : byName;
    if (matches.length > 1) {
      throw new Error(`Dòng ${rowNumber}, cột ${getLabel(column)}: tên "${row[column.key]}" đang bị trùng trong hệ thống.`);
    }
    const selected = matches[0];
    if (!selected || selected.disabled || selected.errorMessage) {
      throw new Error(`Dòng ${rowNumber}, cột ${getLabel(column)}: tên "${row[column.key]}" không tồn tại trong hệ thống.`);
    }
    row[column.key] = selected.value;
  });
}

function normalizeLookupValue(value) {
  return String(value ?? "").trim().toLocaleLowerCase("vi");
}

function validateForm(row, columns, rowNumber) {
  const formData = new FormData();
  columns.filter((column) => !column.formHidden).forEach((column) => {
    formData.set(column.key, row[column.key] ?? "");
  });
  const errors = validateGenericEntityForm({ columns, formData, isEdit: false });
  if (hasErrors(errors)) {
    throw new Error(`Dòng ${rowNumber}: ${Object.values(errors).join(" ")}`);
  }
}

function validateDuplicates(rows, existingRows, columns) {
  const uniqueColumns = columns.filter(
    (column) => column.primaryKey || UNIQUE_FIELD_KEYS.has(column.key.toLowerCase()),
  );
  uniqueColumns.forEach((column) => {
    const existingValues = new Set(
      existingRows
        .map((row) => normalizeUniqueValue(row[column.key]))
        .filter(Boolean),
    );
    const importedValues = new Set();
    rows.forEach(({ data, rowNumber }) => {
      const value = normalizeUniqueValue(data[column.key]);
      if (!value) return;
      if (existingValues.has(value)) {
        throw new Error(`Dòng ${rowNumber}, cột ${column.key}: giá trị đã tồn tại trong hệ thống.`);
      }
      if (importedValues.has(value)) {
        throw new Error(`Dòng ${rowNumber}, cột ${column.key}: giá trị bị trùng trong file.`);
      }
      importedValues.add(value);
    });
  });
}

function normalizeUniqueValue(value) {
  return String(value ?? "").trim().toLocaleLowerCase("vi");
}

export async function parseEntityExcel({ buildExtraPayload, columns, existingRows, file }) {
  if (!file?.name?.toLowerCase().endsWith(".xlsx")) {
    throw new Error("Chỉ chấp nhận file Excel định dạng .xlsx.");
  }
  if (file.size > MAX_FILE_SIZE) {
    throw new Error("File Excel không được vượt quá 10 MB.");
  }
  const { default: ExcelJS } = await import("exceljs");
  const workbook = new ExcelJS.Workbook();
  try {
    await workbook.xlsx.load(await file.arrayBuffer());
  } catch {
    throw new Error("Không đọc được file Excel. File có thể bị lỗi hoặc không đúng định dạng .xlsx.");
  }
  const sheet = workbook.getWorksheet(DATA_SHEET);
  if (!sheet) throw new Error(`Không tìm thấy sheet ${DATA_SHEET}. Hãy tải và dùng đúng file mẫu.`);

  const importColumns = getImportColumns(columns);
  validateHeaders(sheet, importColumns);
  const sourceRows = [];
  sheet.eachRow({ includeEmpty: false }, (excelRow, rowNumber) => {
    if (rowNumber === 1) return;
    const data = {};
    importColumns.forEach((column, index) => {
      data[column.key] = readCellValue(excelRow.getCell(index + 1), column, rowNumber);
    });
    if (Object.values(data).every((value) => value === "")) return;
    sourceRows.push({ data, rowNumber });
  });

  if (!sourceRows.length) throw new Error("File chưa có dòng dữ liệu nào để nhập.");
  if (sourceRows.length > MAX_IMPORT_ROWS) {
    throw new Error(`Mỗi lần chỉ được nhập tối đa ${MAX_IMPORT_ROWS} dòng.`);
  }

  const acceptedRows = [];
  sourceRows.forEach(({ data, rowNumber }) => {
    applyDefaults(data, columns, acceptedRows, existingRows);
    validateOptions(data, importColumns, rowNumber);
    validateForm(data, columns, rowNumber);
    if (buildExtraPayload) {
      const formData = new FormData();
      Object.entries(data).forEach(([key, value]) => formData.set(key, value ?? ""));
      Object.assign(data, buildExtraPayload({ formData, isEdit: false }));
    }
    acceptedRows.push(data);
  });
  validateDuplicates(
    acceptedRows.map((data, index) => ({ data, rowNumber: sourceRows[index].rowNumber })),
    existingRows,
    columns,
  );
  return acceptedRows;
}
