const MAU_EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const MAU_SO_DIEN_THOAI = /^\d{10,13}$/;

function getFieldLabel(cot) {
  return cot?.displayLabel ?? cot?.tableLabel ?? cot?.label ?? cot?.key ?? "Trường dữ liệu";
}

export function validateGenericEntityForm({ columns, formData, isEdit }) {
  const loiTheoTruong = {};
  const danhSachCotTrongForm = columns.filter((cot) => !cot.formHidden);

  danhSachCotTrongForm.forEach((cot) => {
    const dangSuaKhoaChinh = cot.primaryKey && isEdit;
    if (dangSuaKhoaChinh) return;

    const giaTriGoc = formData.get(cot.key);
    const giaTri = typeof giaTriGoc === "string" ? giaTriGoc.trim() : giaTriGoc;
    const tenHienThi = getFieldLabel(cot);

    const biBoTrong = giaTri === null || giaTri === undefined || giaTri === "";
    const khoaChinhBiKhoa = cot.primaryKey && (isEdit || cot.autoGenerated);
    const batBuocNhap =
      cot.required !== false &&
      !(isEdit && cot.requiredOnCreate) &&
      !khoaChinhBiKhoa;

    if (isEdit && cot.keepExistingWhenBlank && biBoTrong) return;

    if (batBuocNhap && biBoTrong) {
      loiTheoTruong[cot.key] = `${tenHienThi} không được để trống.`;
      return;
    }

    if (biBoTrong) return;

    if (cot.maxLength && String(giaTri).length > cot.maxLength) {
      loiTheoTruong[cot.key] = `${tenHienThi} không được vượt quá ${cot.maxLength} ký tự.`;
      return;
    }

    const loiTheoTenTruong = validateByFieldName(cot.key, giaTri, tenHienThi, cot);
    if (loiTheoTenTruong) {
      loiTheoTruong[cot.key] = loiTheoTenTruong;
    }
  });

  return loiTheoTruong;
}

export function hasErrors(errors) {
  return Object.keys(errors).length > 0;
}

function validateByFieldName(key, value, label, column) {
  const tenTruong = key.toLowerCase();
  const namHienTai = new Date().getFullYear();

  if (tenTruong.includes("email") && !MAU_EMAIL.test(value)) {
    return `${label} không đúng định dạng. Ví dụ: name@example.com.`;
  }

  const laTruongSoDienThoai = [
    "sdt",
    "sđt",
    "sodienthoai",
    "sốđiệnthoại",
    "phone",
    "dienthoai",
  ].some((tuKhoa) => tenTruong.includes(tuKhoa));

  if (laTruongSoDienThoai && !MAU_SO_DIEN_THOAI.test(value)) {
    return `${label} phải gồm 10-13 chữ số.`;
  }

  if (tenTruong === "user" && /\s/.test(value)) {
    return `${label} không được chứa khoảng trắng.`;
  }

  const laTruongSo =
    column.inputType === "number" ||
    ["namsinh", "namxb", "soluong"].includes(tenTruong);

  if (laTruongSo) {
    const giaTriSo = Number(value);

    if (Number.isNaN(giaTriSo)) {
      return `${label} phải là số hợp lệ.`;
    }

    if (tenTruong === "soluong" && giaTriSo < 0) {
      return `${label} không được nhỏ hơn 0.`;
    }

    const laTruongNam = ["namsinh", "namxb"].includes(tenTruong);
    if (laTruongNam && (giaTriSo < 1900 || giaTriSo > namHienTai)) {
      return `${label} phải nằm trong khoảng 1900-${namHienTai}.`;
    }
  }

  return "";
}
