const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const PHONE_PATTERN = /^\d{10,12}$/;

function getFieldLabel(column) {
  return column?.displayLabel ?? column?.tableLabel ?? column?.label ?? column?.key ?? "Trường dữ liệu";
}

export function validateGenericEntityForm({ columns, formData, isEdit }) {
  const errors = {};
  const formColumns = columns.filter((column) => !column.formHidden);

  formColumns.forEach((column) => {
    if (column.primaryKey && isEdit) return;

    const rawValue = formData.get(column.key);
    const value = typeof rawValue === "string" ? rawValue.trim() : rawValue;
    const label = getFieldLabel(column);
    const isBlank = value === null || value === undefined || value === "";
    const isLockedPrimaryKey = column.primaryKey && (isEdit || column.autoGenerated);
    const isRequired = column.required !== false && !(isEdit && column.requiredOnCreate) && !isLockedPrimaryKey;

    if (isEdit && column.keepExistingWhenBlank && isBlank) return;

    if (isRequired && isBlank) {
      errors[column.key] = `${label} không được để trống.`;
      return;
    }

    if (isBlank) return;

    const customMessage = validateByFieldName(column.key, value, label, column);
    if (customMessage) errors[column.key] = customMessage;
  });

  return errors;
}

export function hasErrors(errors) {
  return Object.keys(errors).length > 0;
}

function validateByFieldName(key, value, label, column) {
  const normalizedKey = key.toLowerCase();
  const currentYear = new Date().getFullYear();

  if (normalizedKey.includes("email") && !EMAIL_PATTERN.test(value)) {
    return `${label} không đúng định dạng. Ví dụ: name@example.com.`;
  }

  if (["sdt", "sđt", "sodienthoai", "sốđiệnthoại", "phone", "dienthoai"].some((part) => normalizedKey.includes(part))) {
    if (!PHONE_PATTERN.test(value)) return `${label} phải gồm 10-12 chữ số.`;
  }

  if (normalizedKey === "user" && /\s/.test(value)) {
    return `${label} không được chứa khoảng trắng.`;
  }

  if (column.inputType === "number" || ["namsinh", "namxb", "soluong"].includes(normalizedKey)) {
    const numberValue = Number(value);

    if (Number.isNaN(numberValue)) return `${label} phải là số hợp lệ.`;
    if (normalizedKey === "soluong" && numberValue < 0) return `${label} không được nhỏ hơn 0.`;
    if (["namsinh", "namxb"].includes(normalizedKey) && (numberValue < 1900 || numberValue > currentYear)) {
      return `${label} phải nằm trong khoảng 1900-${currentYear}.`;
    }
  }

  return "";
}
