import DataTablePage from "@/components/common/DataTable/DataTablePage";

function NhaXuatBanView() {
  return (
    <DataTablePage
      apiModule="nhaxuatban"
      columns={[
        { key: "MaNXB", label: "MaNXB", displayLabel: "Mã NXB", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenNXB", label: "TenNXB", displayLabel: "Tên NXB", widthValue: 190 },
        { key: "DiaChi", label: "DiaChi", displayLabel: "Địa chỉ", widthValue: 220 },
        { key: "Email", label: "Email", displayLabel: "Email", widthValue: 220 },
        { key: "Sdt", label: "Sdt", displayLabel: "Số điện thoại", widthValue: 160 },
      ]}
      entityName="Nhà xuất bản"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã hoặc tên nhà xuất bản..."
      title="Quản lý Nhà xuất bản"
    />
  );
}

export default NhaXuatBanView;
