import DataTablePage from "@/components/common/DataTable/DataTablePage";

const currentYear = new Date().getFullYear();

function DocGiaView() {
  return (
    <DataTablePage
      apiModule="docgia"
      columns={[
        {
          key: "MaDG",
          label: "MaDG",
          tableLabel: "Mã ĐG",
          displayLabel: "Mã độc giả",
          autoGenerated: true,
          generatedPrefix: "DG",
          generatedWidth: 3,
          primaryKey: true,
          maxLength: 10,
          widthValue: 92,
        },
        {
          key: "TenDG",
          label: "TenDG",
          tableLabel: "Độc giả",
          displayLabel: "Tên độc giả",
          maxLength: 50,
          widthValue: 118,
        },
        {
          key: "NamSinh",
          label: "NamSinh",
          tableLabel: "Năm sinh",
          displayLabel: "Năm sinh",
          inputType: "number",
          required: false,
          min: 1900,
          max: currentYear,
          widthValue: 82,
        },
        {
          key: "GioiTinh",
          label: "GioiTinh",
          tableLabel: "GT",
          displayLabel: "Giới tính",
          maxLength: 10,
          options: ["Nam", "Nữ", "Khác"].map((value) => ({ label: value, value })),
          widthValue: 64,
        },
        {
          key: "DiaChi",
          label: "DiaChi",
          displayLabel: "Địa chỉ",
          maxLength: 100,
          widthValue: 112,
        },
        {
          key: "Email",
          label: "Email",
          displayLabel: "Email",
          maxLength: 50,
          widthValue: 118,
        },
        {
          key: "Sdt",
          label: "Sdt",
          tableLabel: "SĐT",
          displayLabel: "Số điện thoại",
          maxLength: 13,
          widthValue: 96,
        },
      ]}
      entityName="Độc giả"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã, tên hoặc số điện thoại..."
      title="Quản lý Độc giả"
    />
  );
}

export default DocGiaView;
