import DataTablePage from "@/components/common/DataTable/DataTablePage";
import { useApiLists } from "@/hooks/useApiLists";
import { createLookup } from "@/utils/lookup";

const currentYear = new Date().getFullYear();

function DocGiaView() {
  const { data } = useApiLists(["khoa", "lop"]);
  const faculties = data.khoa ?? [];
  const classes = data.lop ?? [];

  const facultyNames = createLookup(faculties, "MaKhoa", "TenKhoa");
  const classNames = createLookup(classes, "MaLop", "TenLop");

  return (
    <DataTablePage
      apiModule="docgia"
      columns={[
        {
          key: "MaDG",
          label: "MaDG",
          tableLabel: "Mã ĐG",
          displayLabel: "Mã độc giả",
          autoGenerated: true,
          generatedPrefix: "DG",
          generatedWidth: 3,
          primaryKey: true,
          maxLength: 10,
          widthValue: 92,
        },
        {
          key: "TenDG",
          label: "TenDG",
          tableLabel: "Độc giả",
          displayLabel: "Tên độc giả",
          maxLength: 50,
          widthValue: 118,
        },
        {
          key: "MaKhoa",
          label: "MaKhoa",
          displayLabel: "Khoa",
          maxLength: 10,
          displayValue: (row) => facultyNames[row.MaKhoa] ?? row.MaKhoa,
          options: faculties.map((item) => ({
            label: `${item.MaKhoa} - ${item.TenKhoa}`,
            value: item.MaKhoa,
          })),
          widthValue: 118,
        },
        {
          key: "MaLop",
          label: "MaLop",
          displayLabel: "Lớp",
          maxLength: 10,
          displayValue: (row) => classNames[row.MaLop] ?? row.MaLop,
          dependsOn: "MaKhoa",
          dependencyPlaceholder: "-- Chọn khoa trước --",
          options: ({ MaKhoa }) =>
            classes
              .filter((item) => item.MaKhoa === MaKhoa)
              .map((item) => ({
                label: `${item.MaLop} - ${item.TenLop}`,
                value: item.MaLop,
              })),
          widthValue: 92,
        },
        {
          key: "NamSinh",
          label: "NamSinh",
          tableLabel: "Năm sinh",
          displayLabel: "Năm sinh",
          inputType: "number",
          required: false,
          min: 1900,
          max: currentYear,
          widthValue: 82,
        },
        {
          key: "GioiTinh",
          label: "GioiTinh",
          tableLabel: "GT",
          displayLabel: "Giới tính",
          maxLength: 10,
          options: ["Nam", "Nữ", "Khác"].map((value) => ({ label: value, value })),
          widthValue: 64,
        },
        {
          key: "DiaChi",
          label: "DiaChi",
          displayLabel: "Địa chỉ",
          maxLength: 100,
          widthValue: 112,
        },
        {
          key: "Email",
          label: "Email",
          displayLabel: "Email",
          maxLength: 50,
          widthValue: 118,
        },
        {
          key: "Sdt",
          label: "Sdt",
          tableLabel: "SĐT",
          displayLabel: "Số điện thoại",
          maxLength: 13,
          widthValue: 96,
        },
      ]}
      entityName="Độc giả"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã, tên hoặc số điện thoại..."
      title="Quản lý Độc giả"
    />
  );
}

export default DocGiaView;
