import DataTablePage from "@/components/common/DataTablePage";

function TacGiaView() {
  return (
    <DataTablePage
      apiModule="tacgia"
      columns={[
        { key: "MaTG", label: "MaTG", displayLabel: "Mã tác giả", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenTG", label: "TenTG", displayLabel: "Tên tác giả", widthValue: 220 },
        { key: "NamSinh", label: "NamSinh", displayLabel: "Năm sinh", inputType: "number", required: false, widthValue: 110 },
        {
          key: "GioiTinh",
          label: "GioiTinh",
          displayLabel: "Giới tính",
          options: ["Nam", "Nữ", "Khác"].map((value) => ({ label: value, value })),
          widthValue: 100,
        },
        { key: "QuocTich", label: "QuocTich", displayLabel: "Quốc tịch", widthValue: 150 },
      ]}
      entityName="Tác giả"
      searchPlaceholder="Tìm mã hoặc tên tác giả..."
      title="Quản lý Tác giả"
    />
  );
}

export default TacGiaView;
