import DataTablePage from "@/components/common/DataTablePage";
import { useApiLists } from "@/hooks/useApiLists";
import { createLookup } from "@/utils/lookup";

function LopView() {
  const { data } = useApiLists(["khoa"]);
  const faculties = data.khoa ?? [];
  const facultyNames = createLookup(faculties, "MaKhoa", "TenKhoa");

  return (
    <DataTablePage
      apiModule="lop"
      columns={[
        { key: "MaLop", label: "MaLop", displayLabel: "Mã lớp", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenLop", label: "TenLop", displayLabel: "Tên lớp", widthValue: 170 },
        {
          key: "MaKhoa",
          label: "MaKhoa",
          displayLabel: "Khoa",
          displayValue: (row) => facultyNames[row.MaKhoa] ?? row.MaKhoa,
          options: faculties.map((faculty) => ({
            label: `${faculty.MaKhoa} - ${faculty.TenKhoa}`,
            value: faculty.MaKhoa,
          })),
          required: false,
          widthValue: 250,
        },
      ]}
      entityName="Lớp"
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã lớp hoặc tên lớp..."
      title="Quản lý Lớp"
    />
  );
}

export default LopView;
