import DataTablePage from "@/components/common/DataTable/DataTablePage";
import { useApiLists } from "@/hooks/useApiLists";
import { api } from "@/lib/api";
import { SachMuonDetail, SachMuonSelector } from "@/views/muontra/components/SachMuonContent";
import { formatCurrency } from "@/views/muontra/muonTraUtils";
import { createLookup } from "@/utils/lookup";

function MuonTraView() {
  const { data } = useApiLists(["docgia", "nhanvien", "sach"]);
  const readers = data.docgia ?? [];
  const employees = data.nhanvien ?? [];
  const books = data.sach ?? [];
  const readerNames = createLookup(readers, "MaDG", "TenDG");
  const employeeNames = createLookup(employees, "MaNV", "TenNV");

  return (
    <DataTablePage
      apiModule="muontra"
      buildExtraPayload={buildLoanDetailsPayload}
      columns={[
        { key: "MaMT", label: "MaMT", displayLabel: "Mã mượn trả", autoGenerated: true, primaryKey: true, widthValue: 130 },
        {
          key: "MaDG", label: "MaDG", displayLabel: "Độc giả",
          displayValue: (row) => row.TenDG ?? readerNames[row.MaDG] ?? row.MaDG,
          options: readers.map((reader) => ({ label: `${reader.MaDG} - ${reader.TenDG}`, value: reader.MaDG })),
          widthValue: 190,
        },
        {
          key: "MaNV", label: "MaNV", displayLabel: "Nhân viên",
          displayValue: (row) => row.TenNV ?? employeeNames[row.MaNV] ?? row.MaNV,
          options: employees.map((employee) => ({ label: `${employee.MaNV} - ${employee.TenNV}`, value: employee.MaNV })),
          widthValue: 160,
        },
        { key: "NgayMuon", label: "NgayMuon", displayLabel: "Ngày mượn", inputType: "date", required: false, widthValue: 140 },
        { key: "HanTra", label: "HanTra", displayLabel: "Hạn trả", inputType: "date", widthValue: 140 },
        {
          key: "NgayTra",
          label: "NgayTra",
          displayLabel: "Ngày trả",
          inputType: "date",
          formHidden: true,
          widthValue: 140,
        },
        {
          key: "TienPhat",
          label: "TienPhat",
          displayLabel: "Tiền phạt",
          displayValue: (row) => formatCurrency(row.TienPhat ?? 0),
          formHidden: true,
          widthValue: 140,
        },
        {
          key: "TrangThai",
          label: "TrangThai",
          displayLabel: "Trạng thái",
          badge: true,
          formHidden: true,
          displayValue: (row) => row.TrangThai,
          widthValue: 140,
        },
      ]}
      entityName="Mượn trả"
      renderDetailExtra={({ row, updateRow }) => (
        <SachMuonDetail
          books={books}
          details={row.ChiTiet ?? []}
          onReturned={async ({ NgayTra }) => {
            const response = await api.returnBooks(row.MaMT, NgayTra);
            updateRow(response.data);
          }}
          row={row}
        />
      )}
      renderFormExtra={({ row }) => (
        <SachMuonSelector books={books} details={row?.ChiTiet ?? []} ticketId={row?.MaMT} />
      )}
      pagination
      pageSize={10}
      searchPlaceholder="Tìm mã mượn trả hoặc độc giả..."
      title="Quản lý Mượn trả"
    />
  );
}

function buildLoanDetailsPayload({ formData }) {
  return {
    ChiTiet: Array.from(formData.entries())
      .filter(([key]) => key.startsWith("SachMuon["))
      .map(([key, value]) => ({
        MaSach: key.slice("SachMuon[".length, -1),
        SoLuong: Number(value),
      })),
  };
}

export default MuonTraView;
